/*
=============================================================
Magnitude Analysis
=============================================================
Purpose:
    Analyze the size and distribution of key business
    metrics across different dimensions such as
    customers, products, categories, and countries.

    This analysis helps identify which segments
    contribute the most in terms of volume, count,
    and revenue, enabling better business insights
    and decision-making.
*/


--Find total customers by countries
SELECT 
	country,
	COUNT(customer_id) total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

--Find total customers by gender
SELECT
	gender,
	COUNT(customer_key) total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

--Find total product by categories
SELECT 
	category,
	COUNT(product_key) total_product
FROM gold.dim_products
GROUP BY category
ORDER BY total_product DESC

--What is the average cost in each categories
SELECT 
	category,
	AVG(cost) average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC

-- what is the total reveneu generated for each categories
SELECT
	p.category,
	SUM(f.sales_amount) total_sales
FROM gold.fact_sales f
LEFT JOIN
gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_sales DESC

-- what is the total reveneu generated by each coustomer
SELECT
	c.first_name,
	c.last_name,
	c.customer_key,
	SUM(f.sales_amount) customer_total
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY 
	c.first_name,
	c.last_name,
	c.customer_key
ORDER BY customer_total DESC

-- what is the distribution of sold items across the countries
SELECT
	c.country,
	SUM(f.quantity) total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC
